default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1q2w34567
  host: localhost

development:
  <<: *default
  database: gym_development

test:
  <<: *default
  database: gym_test

production:
  <<: *default
  database: gym_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
